# Change these first
owner: fef1312 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: fef's blog
    url: https://fef.moe/
    maxResponseTime: 1000
  - name: Garbage Collector
    url: https://gc.fef.moe/login
    maxResponseTime: 3000
  - name: Gay Git
    url: https://git.bsd.gay/
    maxResponseTime: 2000
  - name: Gay CI
    url: https://ci.bsd.gay/
    maxResponseTime: 1000
  - name: Arch Linux Package Mirror
    url: https://pkg.fef.moe/archlinux/
    maxResponseTime: 500
  - name: SMTP (Asuna)
    check: "tcp-ping"
    url: mail.fef.moe
    port: 25
  - name: DNS 1 (Rem)
    check: "tcp-ping"
    url: 78.47.78.184
    port: 53
  - name: DNS 2 (Astolfo)
    check: "tcp-ping"
    url: 78.46.85.216
    port: 53
  - name: DNS 3 (Kaho)
    check: "tcp-ping"
    url: 188.68.36.246
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fef.moe
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: UwUptime
  introTitle: "Tiddies and Balls"
  introMessage: My infrastructure is just like me: unstable.
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://fef.moe/about/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

user-agent: fef1312
robotsText: "User-agent: *\nDisallow: /\n"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
